"""
organize.py - Housekeeping for the project.

Run this:
    - before commits, to keep the repo tidy
    - when outputs/ has too many old runs after multiple --refresh
    - to regenerate INDEX.md after a fresh analysis run

What it does:
    1. Snapshot current outputs/ to archive/YYYY-MM-DD/ if older than 7 days
    2. Generate outputs/INDEX.md listing what's there and when it was made
    3. Report orphan files (in outputs/ but no matching analysis_*.py exists)
    4. Report drafts/ status (Word docs by modification date)

It does NOT:
    - Touch data/ (that's the DB cache, separate concern)
    - Delete anything (only moves to archive)
    - Modify analysis modules or db.py
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).parent
OUTPUTS = ROOT / "outputs"
ARCHIVE = ROOT / "archive"
DRAFTS = ROOT / "drafts"
ANALYSIS_PATTERN = re.compile(r"^analysis_(\w+)\.py$")

ARCHIVE_THRESHOLD_DAYS = 7


# --------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------- #

def _list_analysis_modules() -> set[str]:
    """Return prefixes like {'anova', 'chi_square', 'correlation', ...}."""
    prefixes = set()
    for p in ROOT.glob("analysis_*.py"):
        m = ANALYSIS_PATTERN.match(p.name)
        if m:
            prefixes.add(m.group(1))
    return prefixes


def _output_to_module(filename: str) -> str | None:
    """
    Map an output file to its source module prefix.
    Naming convention used by analysis modules:
        analysis_anova.py        → anova_results.txt, anova_boxplot.png
        analysis_chi_square.py   → chi_square_dow.txt
        analysis_correlation.py  → correlation.txt, correlation_scatter.png
        analysis_stl.py          → stl_results.txt, stl_decomposition.png
        analysis_changepoint.py  → changepoint.txt, changepoint.png
    """
    stem = Path(filename).stem
    # Try prefix match against known module names, longest first to avoid
    # 'chi' matching 'chi_square'.
    for prefix in sorted(_list_analysis_modules(), key=len, reverse=True):
        if stem.startswith(prefix):
            return prefix
    return None


def _human_size(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024:
            return f"{n:.0f} {unit}"
        n /= 1024
    return f"{n:.0f} TB"


def _human_age(ts: float) -> str:
    age = dt.datetime.now() - dt.datetime.fromtimestamp(ts)
    if age.days >= 1:
        return f"{age.days}d ago"
    hours = age.seconds // 3600
    if hours >= 1:
        return f"{hours}h ago"
    return f"{age.seconds // 60}m ago"


# --------------------------------------------------------------------- #
# Tasks
# --------------------------------------------------------------------- #

def archive_old(dry_run: bool = False) -> int:
    """Move outputs/ files older than ARCHIVE_THRESHOLD_DAYS into archive/YYYY-MM-DD/."""
    if not OUTPUTS.exists():
        print("⚠️  outputs/ doesn't exist — nothing to archive.")
        return 0

    cutoff = dt.datetime.now() - dt.timedelta(days=ARCHIVE_THRESHOLD_DAYS)
    moved = 0
    for f in OUTPUTS.iterdir():
        if not f.is_file() or f.name == "INDEX.md":
            continue
        mtime = dt.datetime.fromtimestamp(f.stat().st_mtime)
        if mtime < cutoff:
            target_dir = ARCHIVE / mtime.strftime("%Y-%m-%d")
            target_dir.mkdir(parents=True, exist_ok=True)
            target = target_dir / f.name
            print(f"   {'[dry-run] ' if dry_run else ''}archive: {f.name} → archive/{target_dir.name}/")
            if not dry_run:
                shutil.move(str(f), str(target))
            moved += 1
    if moved == 0:
        print("   (nothing older than 7 days)")
    return moved


def generate_index() -> None:
    """Write outputs/INDEX.md listing current files with timestamps."""
    if not OUTPUTS.exists():
        print("⚠️  outputs/ doesn't exist — skipping index.")
        return

    files = sorted(
        [f for f in OUTPUTS.iterdir() if f.is_file() and f.name != "INDEX.md"],
        key=lambda f: f.stat().st_mtime,
        reverse=True,
    )

    lines = [
        "# Outputs index",
        "",
        f"_Auto-generated by `organize.py` at {dt.datetime.now():%Y-%m-%d %H:%M}._",
        "",
        "| File | Module | Size | Modified |",
        "|------|--------|------|----------|",
    ]
    for f in files:
        module = _output_to_module(f.name) or "—"
        size = _human_size(f.stat().st_size)
        age = _human_age(f.stat().st_mtime)
        lines.append(f"| `{f.name}` | {module} | {size} | {age} |")

    if not files:
        lines.append("| _(empty — run `python main.py` to generate)_ | | | |")

    (OUTPUTS / "INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"   wrote {OUTPUTS / 'INDEX.md'} ({len(files)} files indexed)")


def find_orphans() -> list[Path]:
    """Files in outputs/ that don't match any current analysis module."""
    if not OUTPUTS.exists():
        return []
    orphans = []
    for f in OUTPUTS.iterdir():
        if not f.is_file() or f.name == "INDEX.md":
            continue
        if _output_to_module(f.name) is None:
            orphans.append(f)
    if orphans:
        print(f"   ⚠️  {len(orphans)} orphan file(s) (no matching analysis_*.py):")
        for f in orphans:
            print(f"      {f.name}")
    else:
        print("   (none)")
    return orphans


def list_drafts() -> None:
    """Just informational — show Word docs in drafts/ by date."""
    if not DRAFTS.exists():
        print("   (drafts/ doesn't exist yet)")
        return
    docs = sorted(
        DRAFTS.glob("*.docx"),
        key=lambda f: f.stat().st_mtime,
        reverse=True,
    )
    if not docs:
        print("   (no .docx files)")
        return
    for d in docs:
        size = _human_size(d.stat().st_size)
        age = _human_age(d.stat().st_mtime)
        print(f"   {d.name:40s}  {size:>8s}  {age}")


# --------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------- #

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show what would happen without moving files",
    )
    args = parser.parse_args()

    print("📁 Project housekeeping")
    print("=" * 60)

    print("\n[1/4] Archiving old outputs...")
    archive_old(dry_run=args.dry_run)

    print("\n[2/4] Generating outputs/INDEX.md...")
    generate_index()

    print("\n[3/4] Checking for orphan output files...")
    find_orphans()

    print("\n[4/4] Drafts status...")
    list_drafts()

    print("\n✅ Done.")


if __name__ == "__main__":
    main()
